name: Continuous Integration (CI) 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install libreadline-dev -y
    - name: Build
      run: make
    - name: Run Checks
      run: make check